apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    field.cattle.io/description: pod to provide an ui to the docker registry
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["10.0.1.6"],"port":443,"protocol":"HTTPS","serviceName":"default:docker-registry-ui","ingressName":"default:registry-ingress","hostname":"nailloux.registry.com","path":"/","allNodes":false}]
  creationTimestamp: '2026-01-08T12:24:40Z'
  generation: 35
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-docker-registry-ui
  name: docker-registry-ui
  namespace: default
  resourceVersion: '834847'
  uid: b54ad288-266e-463f-8854-5b1c7ab3ed02
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-docker-registry-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-docker-registry-ui
      namespace: default
    spec:
      containers:
        - env:
            - name: NGINX_PROXY_PASS_URL
              value: http://docker-registry:5000
            - name: DELETE_IMAGES
              value: 'true'
            - name: SINGLE_REGISTRY
              value: 'true'
          image: joxit/docker-registry-ui
          imagePullPolicy: Always
          name: docker-ui-container
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2026-01-08T12:24:54Z'
      lastUpdateTime: '2026-01-08T12:24:54Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2026-01-08T12:24:41Z'
      lastUpdateTime: '2026-01-08T12:29:52Z'
      message: ReplicaSet "docker-registry-ui-6bcdf94f8b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 35
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1