apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["10.0.1.6"],"port":443,"protocol":"HTTPS","serviceName":"default:docker-registry-ui","ingressName":"default:registry-ingress","hostname":"nailloux.registry.com","path":"/","allNodes":false}]
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
  generation: 4
  name: registry-ingress
  namespace: default
spec:
  rules:
    - host: nailloux.registry.com
      http:
        paths:
          - backend:
              service:
                name: docker-registry-ui
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - nailloux.registry.com
      secretName: registry.tls
